
--call delete_event (event_id)

DELIMITER //

CREATE PROCEDURE delete_event(
   eid int
)
BEGIN	

  DELETE FROM STUDENT_EVENT_MAP WHERE EVENT_ID=eid;

  DELETE FROM ORGANIZER_EVENT_MAP WHERE EVENT_ID=eid;

  DELETE FROM EVENT_INTEREST_MAP WHERE EVENT_ID=eid;

  DELETE FROM EVENTS WHERE ID=eid;

END

// DELIMITER ;